# Generated by Django 4.1.3 on 2022-11-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangundatar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materimatematika',
            old_name='namabangundatar',
            new_name='nama',
        ),
    ]
