# Generated by Django 4.1.3 on 2022-11-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangundatar', '0002_rename_namabangundatar_materimatematika_nama'),
    ]

    operations = [
        migrations.CreateModel(
            name='MahasiswaFkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=300, null=True)),
                ('nim', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=100)),
                ('ttl', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('fakultas', models.CharField(max_length=100)),
                ('prodi', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=300)),
                ('foto', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
