# Generated by Django 4.1.3 on 2022-11-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangundatar', '0003_mahasiswafkip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MahasiswaFkip',
        ),
    ]
